import type { ContractEvent } from "@axion/types";

export const events: ContractEvent[] = [
  // ---- Arena Multiuso Zona Norte ----
  {
    id: "evt-arena-01",
    projectId: "prj-arena",
    timestamp: "2025-06-25T08:30:00-03:00",
    title: "Notificação formal do cliente sobre atraso no cronograma",
    description: "Prefeitura de Itaguaí notifica atraso e cobra plano de recuperação, citando possível multa contratual.",
    sourceType: "EMAIL",
    evidence: { sourceType: "EMAIL", label: "Gmail — Notificação de Atraso Contratual", locator: "gmail://axion.com.br/inbox/msg-2025-0625-1", emailId: "em-arena-01" },
    categories: ["NOTIFICACOES", "PRAZO", "MULTAS"],
    status: "EM_ANALISE",
    crossReferences: [
      { kind: "CONTRATO_ADITIVO", refType: "CLAUSE", refId: "cls-arena-02", note: "Cláusula de multa por atraso." },
      { kind: "CRONOGRAMA", refType: "SCHEDULE_ACTIVITY", refId: "sch-arena-02", note: "Atividade em atraso." },
    ],
    aiAssessment: { findingType: "IMPACTO_POTENCIAL", severity: "ALTA", summary: "Notificação inicia prazo de defesa; recomenda-se resposta baseada em evento de força maior já registrado.", confidence: 0.88, requiresHumanReview: true },
    createdBy: "sistema",
  },
  {
    id: "evt-arena-02",
    projectId: "prj-arena",
    timestamp: "2025-04-18T11:00:00-03:00",
    title: "RFI-01 recebida: especificação de estrutura metálica da cobertura",
    description: "Cliente formaliza RFI-01 questionando especificação técnica da estrutura metálica de cobertura.",
    sourceType: "EDITAL_RFI_RFP",
    evidence: { sourceType: "EDITAL_RFI_RFP", label: "RFI-01 — Estrutura Metálica da Cobertura", locator: "recebidos-cliente://prj-arena/RFI/RFI-01.pdf", documentId: "doc-arena-rfi-01" },
    categories: ["ESCOPO", "ALTERACOES_PROJETO"],
    status: "CONFRONTADO",
    crossReferences: [
      { kind: "EDITAL_RFI_RFP", refType: "DOCUMENT", refId: "doc-arena-rfi-01", note: "RFI original do cliente." },
      { kind: "CONTRATO_ADITIVO", refType: "CLAUSE", refId: "cls-arena-03", note: "Prazo contratual de resposta a RFIs." },
    ],
    aiAssessment: { findingType: "CONFLITO", severity: "MEDIA", summary: "Especificação questionada diverge do memorial descritivo da proposta vigente.", confidence: 0.81, requiresHumanReview: true },
    createdBy: "sistema",
  },
  {
    id: "evt-arena-03",
    projectId: "prj-arena",
    timestamp: "2025-12-15T16:00:00-03:00",
    title: "Cliente cobra aplicação de multa por atraso",
    description: "E-mail formal cobra aplicação de multa contratual por atraso, referenciando notificação anterior.",
    sourceType: "EMAIL",
    evidence: { sourceType: "EMAIL", label: "Gmail — Aplicação de Multa Contratual", locator: "gmail://axion.com.br/inbox/msg-2025-1215-1", emailId: "em-arena-02" },
    categories: ["MULTAS", "PENALIDADES", "NOTIFICACOES"],
    status: "EM_ANALISE",
    crossReferences: [
      { kind: "CONTRATO_ADITIVO", refType: "CLAUSE", refId: "cls-arena-02", note: "Cláusula de multa por atraso." },
      { kind: "COMUNICACAO", refType: "EMAIL", refId: "em-arena-01", note: "Notificação formal anterior." },
    ],
    aiAssessment: { findingType: "IMPACTO_POTENCIAL", severity: "CRITICA", summary: "Cobrança formal exige resposta fundamentada nos eventos de força maior já documentados.", confidence: 0.9, requiresHumanReview: true },
    createdBy: "sistema",
  },
  {
    id: "evt-arena-04",
    projectId: "prj-arena",
    timestamp: "2026-01-20T08:45:00-03:00",
    title: "Paralisação por falta de liberação de área pelo cliente",
    description: "Diário de Obra registra paralisação de 5 dias na frente de paisagismo por falta de liberação de área pelo cliente.",
    sourceType: "DIARIO_OBRA",
    evidence: { sourceType: "DIARIO_OBRA", label: "Diário de Obra — Registro 2026-01-20", locator: "diario-obra://prj-arena/registro/1298" },
    categories: ["PRAZO", "RESPONSABILIDADES"],
    status: "EM_ANALISE",
    crossReferences: [
      { kind: "CRONOGRAMA", refType: "SCHEDULE_ACTIVITY", refId: "sch-arena-03", note: "Impacto direto na atividade de paisagismo." },
    ],
    aiAssessment: { findingType: "IMPACTO_POTENCIAL", severity: "ALTA", summary: "Atraso decorre de responsabilidade do cliente e fundamenta extensão de prazo sem ônus à Axion.", confidence: 0.82, requiresHumanReview: true },
    createdBy: "sistema",
  },
  {
    id: "evt-arena-05",
    projectId: "prj-arena",
    timestamp: "2025-02-10T09:00:00-03:00",
    title: "Cronograma baseline aprovado",
    description: "Cronograma físico-financeiro baseline aprovado formalmente no início do contrato.",
    sourceType: "CRONOGRAMA",
    evidence: { sourceType: "CRONOGRAMA", label: "Cronograma Baseline", locator: "drive://prj-arena/cronograma/baseline.pdf", documentId: "doc-arena-cronograma-baseline" },
    categories: ["PRAZO"],
    status: "RESOLVIDO",
    crossReferences: [{ kind: "CRONOGRAMA", refType: "DOCUMENT", refId: "doc-arena-cronograma-baseline", note: "Cronograma aprovado." }],
    aiAssessment: null,
    createdBy: "usr-joao",
  },

  // ---- Complexo Industrial Vetraria ----
  {
    id: "evt-ind-01",
    projectId: "prj-industrial",
    timestamp: "2025-07-25T10:30:00-03:00",
    title: "Solo com capacidade de carga abaixo do informado no edital",
    description: "Sondagem confirmatória identifica capacidade de carga do solo inferior ao laudo anexo ao edital.",
    sourceType: "DIARIO_OBRA",
    evidence: { sourceType: "DIARIO_OBRA", label: "Diário de Obra — Registro 2025-07-25", locator: "diario-obra://prj-industrial/registro/0231" },
    categories: ["ESCOPO", "CUSTO", "ALTERACOES_PROJETO"],
    status: "CONFRONTADO",
    crossReferences: [
      { kind: "EDITAL_RFI_RFP", refType: "DOCUMENT", refId: "doc-ind-edital", note: "Laudo de sondagem anexo ao edital." },
      { kind: "CONTRATO_ADITIVO", refType: "CLAUSE", refId: "cls-ind-02", note: "Responsabilidade do contratante por condições de solo." },
    ],
    aiAssessment: { findingType: "CONFLITO", severity: "CRITICA", summary: "Condição de solo divergente do laudo é responsabilidade do cliente e fundamenta pleito de custo e prazo.", confidence: 0.91, requiresHumanReview: true },
    createdBy: "sistema",
  },
  {
    id: "evt-ind-02",
    projectId: "prj-industrial",
    timestamp: "2025-10-17T08:30:00-03:00",
    title: "Não conformidade em ensaio de solda notificada pelo cliente",
    description: "Vetraria notifica não conformidade em ensaio de solda da estrutura metálica, solicitando plano de ação corretiva.",
    sourceType: "EMAIL",
    evidence: { sourceType: "EMAIL", label: "Gmail — Não Conformidade — Ensaio de Solda", locator: "gmail://axion.com.br/inbox/msg-2025-1017-1", emailId: "em-ind-01" },
    categories: ["RESPONSABILIDADES", "PENALIDADES"],
    status: "RESOLVIDO",
    crossReferences: [],
    aiAssessment: { findingType: "IMPACTO_POTENCIAL", severity: "MEDIA", summary: "Não conformidade pode gerar retenção de medição até comprovação de correção.", confidence: 0.75, requiresHumanReview: true },
    createdBy: "sistema",
  },
  {
    id: "evt-ind-03",
    projectId: "prj-industrial",
    timestamp: "2025-09-05T16:00:00-03:00",
    title: "Variação cambial impacta custo de equipamentos importados",
    description: "ERP registra reajuste de 11% no valor de equipamentos importados, decorrente de variação cambial.",
    sourceType: "ERP",
    evidence: { sourceType: "ERP", label: "ERP — Pedido de Compra PC-4471", locator: "erp://prj-industrial/pedidos-compra/4471" },
    categories: ["CUSTO"],
    status: "EM_ANALISE",
    crossReferences: [{ kind: "CONTRATO_ADITIVO", refType: "CLAUSE", refId: "cls-ind-01", note: "Cláusula de reajuste por variação cambial." }],
    aiAssessment: { findingType: "IMPACTO_POTENCIAL", severity: "MEDIA", summary: "Variação cambial pode ser objeto de reajuste conforme cláusula 7.4.", confidence: 0.71, requiresHumanReview: true },
    createdBy: "usr-fernanda",
  },
  {
    id: "evt-ind-04",
    projectId: "prj-industrial",
    timestamp: "2025-10-25T10:00:00-03:00",
    title: "Aditivo nº 01 formaliza sistema de combate a incêndio",
    description: "Aditivo contratual assinado incluindo escopo adicional de combate a incêndio exigido pelo corpo de bombeiros.",
    sourceType: "CONTRATO",
    evidence: { sourceType: "CONTRATO", label: "Aditivo Contratual nº 01", locator: "drive://prj-industrial/contratos/aditivo-01.pdf" },
    categories: ["ESCOPO", "CUSTO"],
    status: "RESOLVIDO",
    crossReferences: [{ kind: "CONTRATO_ADITIVO", refType: "DOCUMENT", refId: "doc-ind-contrato", note: "Contrato base de referência." }],
    aiAssessment: null,
    createdBy: "usr-fernanda",
  },
  {
    id: "evt-ind-05",
    projectId: "prj-industrial",
    timestamp: "2026-06-26T10:00:00-03:00",
    title: "Cliente sinaliza possível change order para ampliação de área de estocagem",
    description: "Vetraria solicita proposta de change order para ampliação de área de estocagem, fora do escopo original.",
    sourceType: "EMAIL",
    evidence: { sourceType: "EMAIL", label: "Gmail — Ampliação Área de Estocagem", locator: "gmail://axion.com.br/inbox/msg-2026-0626-1", emailId: "em-ind-02" },
    categories: ["CLAIMS_CHANGE_ORDERS", "ESCOPO", "CUSTO"],
    status: "NOVO",
    crossReferences: [{ kind: "CONTRATO_ADITIVO", refType: "DOCUMENT", refId: "doc-ind-contrato", note: "Escopo original de referência." }],
    aiAssessment: { findingType: "INFORMACAO_NOVA", severity: "MEDIA", summary: "Solicitação caracteriza change order formal; recomenda-se elaborar aditivo.", confidence: 0.77, requiresHumanReview: true },
    createdBy: "sistema",
  },
];
